### ISSUE TITLE
Error "unknown shorthand flag: 'n' in -network

### ISSUE THREAD

**Issue by GGDRriedel** [uni-halle/etherpad-lite-docker#1]
Getting the following error: 

```
unknown shorthand flag: 'n' in -network
```

Might be due to me running it in ubuntu 20?

**Comment by felix-itz** [comment]
Double-dash (`--`) is required when supplying command line args in extended format.
https://docs.docker.com/engine/reference/run/#network-settings

**Comment by Rillke** [comment]
i.e. `--network` not `-network`
